### ISSUE TITLE
It is missing dependencies

### ISSUE THREAD

**Issue by Clooloo** [chrono460/godot-orbital-mechanics#1]
I get this errors when I try to run:  E 0:00:00:0227   load_source_code: Attempt to open script 'res://addons/orbit_camera/orbit_camera.gd' resulted in error 'File not found'.
  <C++ Error>    Condition "err" is true. Returning: err
  <C++ Source>   modules/gdscript/gdscript.cpp:1025 @ load_source_code()

**Comment by Puddling** [comment]
The demo needs to use the Orbit Camera addon, you can download it from the Asset Library

**Comment by chrono460** [comment]
Dependency to Orbit Camera addon has been removed in 6fac2c4f6daaff3ab9b19a78251b2798806adcca. This issue will be closed.
